version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodManagerDataBase
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=StrongP@ssw0rd123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:
